---
title: "Ch3_markdown"
author: "Emily"
date: "2024-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo = FALSE, warning = FALSE, message = FALSE}
#Libraries
library(lubridate)
library(scales)

#radii to use
R_inner <- 15
R_outer <- 50

#set time zone to UTC to avoid confusing time zone issues
Sys.setenv(TZ='UTC')

groupdir <- "C:/Users/egrout/Dropbox/coatithon/processed/2022/galaxy/"

#read in functions
source('C:/Users/egrout/Dropbox/coatithon/coatithon_code/coati_function_library.R')

#LOAD DATA
#navigate into directory
setwd(groupdir)

#read in coati ids
load("C:/Users/egrout/Dropbox/coatithon/processed/2022/galaxy/galaxy_coati_ids.RData")

#modify coati ids to only include first 3 letters
coati_ids$name_short <- sapply(coati_ids$name, function(x){return(substr(x,1,3))})

#read in timestamp data #NEED TO CHANGE TO LEVEL2
load("C:/Users/egrout/Dropbox/coatithon/processed/2022/galaxy/galaxy_xy_highres_level1.RData")

#ff_data is the list made from detect_fissions_and_fusions function
ff_data_level1 <- load("C:/Users/egrout/Dropbox/coatithon/processed/2022/galaxy/galaxy_auto_ff_events_characterized.RData")

events <- ff_data$events_detected


```



